spring:
  application:
    name: nexus-payments
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/payments_db}
    username: ${DB_USERNAME:nexus}
    password: ${DB_PASSWORD:nexus}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  flyway:
    locations: classpath:db/migration
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:nexus}
    password: ${RABBITMQ_PASSWORD:nexus}
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 3
          initial-interval: 1000ms
          multiplier: 2.0
          max-interval: 10000ms

payment:
  provider:
    base-url: ${PAYMENT_PROVIDER_BASE_URL:http://localhost:8084}
    connect-timeout: ${PAYMENT_PROVIDER_CONNECT_TIMEOUT:2000}
    read-timeout: ${PAYMENT_PROVIDER_READ_TIMEOUT:5000}

server:
  port: 8083

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
